1.https://github.com/BateVesko/WT32-SC01_01_new/blob/main/Sensors/Sensors/Presure_sensor_graduation/Presure_sensor_graduation_display_14_start_stop_Toni01/ForChatGPT.h
2.https://github.com/BateVesko/WT32-SC01_01_new/blob/main/Sensors/Sensors/Presure_sensor_graduation/Presure_sensor_graduation_display_14_start_stop_Toni01/PWM_generator.h
3.https://github.com/BateVesko/WT32-SC01_01_new/blob/main/Sensors/Sensors/Presure_sensor_graduation/Presure_sensor_graduation_display_14_start_stop_Toni01/Presure_sensor_graduation_display_14_start_stop_Toni01.ino
4.https://github.com/BateVesko/WT32-SC01_01_new/blob/main/Sensors/Sensors/Presure_sensor_graduation/Presure_sensor_graduation_display_14_start_stop_Toni01/button_rect.h
5.https://github.com/BateVesko/WT32-SC01_01_new/blob/main/Sensors/Sensors/Presure_sensor_graduation/Presure_sensor_graduation_display_14_start_stop_Toni01/data_visualize.h
6.https://github.com/BateVesko/WT32-SC01_01_new/blob/main/Sensors/Sensors/Presure_sensor_graduation/Presure_sensor_graduation_display_14_start_stop_Toni01/variable_set_triangles.h
